category: application
doc: |
  Config for a run with Alaukik Saxena's composition space tool.
  
  This is an initial draft application definition for the common NFDI-MatWerk,
  FAIRmat infrastructure use case IUC09 how to improve the organization and
  results storage of the composition space tool and make these data at the
  same time directly understandable for research data management systems
  like NOMAD Oasis.
symbols:
  doc: |
    The symbols used in the schema to specify e.g. dimensions of arrays.
  n_voxel: |
    Number of voxel of discretized domain for analyzed part of the dataset.
  d: |
    The dimensionality of the grid.
  c: |
    The cardinality or total number of cells/grid points.
  n_clst_dict: |
    Number of terms in the composition clustering dictionary
  n_spat_dict: |
    Number of terms in the position clustering dictionary
type: group
NXapm_compositionspace_config(NXobject):
  # by default for appdefs the value of the exists keyword is required unless it is explicitly specified differently
  (NXentry):
    exists: [min, 1, max, 1]
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_compositionspace_config]
