category: application
doc: |
  Config for a run with Alaukik Saxena's composition space tool.
  
  This is an initial draft application definition for the common NFDI-MatWerk,
  FAIRmat infrastructure use case IUC09 how to improve the organization and
  results storage of the composition space tool and make these data at the
  same time directly understandable for research data management systems
  like NOMAD Oasis.
symbols:
  doc: |
    The symbols used in the schema to specify e.g. dimensions of arrays.
  n_voxel: |
    Number of voxel of discretized domain for analyzed part of the dataset.
  d: |
    The dimensionality of the grid.
  c: |
    The cardinality or total number of cells/grid points.
  n_clst_dict: |
    Number of terms in the composition clustering dictionary
  n_spat_dict: |
    Number of terms in the position clustering dictionary
type: group
NXapm_compositionspace_config(NXobject):
  # by default for appdefs the value of the exists keyword is required unless it is explicitly specified differently
  (NXentry):
    exists: [min, 1, max, 1]
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_compositionspace_config]
    config(NXobject):
      (NXidentifier):
        exists: optional
      analysis_identifier(NX_UINT):
        exists: recommended
      reconstruction(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        ranging_definitions(NX_CHAR):
      voxel_size(NX_FLOAT):
        doc: |
          Edge length of the grid that is used to discretize the point cloud in the voxelization step.
        unit: NX_LENGTH
      bics_clusters(NX_UINT):
        doc: |
          TODO
        unit: NX_UNITLESS
      n_phases(NX_UINT):
        doc: |
          TODO
        unit: NX_UNITLESS
      ml_models(NXobject):
        doc: |
          The configuration of the machine learning model used in the segmentation step.
        name(NX_CHAR):
          doc: |
            Name of the model to be used.
        gaussian_mixture(NXobject):
          doc: |
             Configuration for the Gaussian mixture model.
          n_components(NX_UINT):
            doc: |
              TODO
            unit: NX_UNITLESS
          max_iter(NX_UINT):
            doc: |
              TODO
            unit: NX_UNITLESS
          verbose(NX_BOOLEAN):
            doc: |
              Report debug information yes or no.
        random_forest(NXobject):
          doc: |
            Configuration for the random forest model.
          max_depth(NX_UINT):
            doc: |
              TODO
            unit: NX_UNITLESS
          n_estimators(NX_UINT):
            doc: |
              TODO
            unit: NX_UNITLESS
        dbscan(NXobject):
          doc: |
            Configuration for the DBScan used in the clustering step.
          eps(NX_FLOAT):
            doc: |
              TODO
            unit: NX_LENGTH
          min_samples(NX_UINT):
            doc: |
              TODO
            unit: NX_UNITLESS
    common(NXobject): 
      status(NX_CHAR):
      programID(NXprogram):
        exists: [min, 1, max, infty]
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):
