name: Publish Sphinx Docs to GitHub Pages
on: [push]

# see: https://sphinx-notes.github.io/pages/
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Install build requirements
      run: |
        pip install -r requirements.txt

    - name: Diagnostic
      run: |
        pip list

    - name: Run the test suite
      run: |
        python utils/test_suite.py

    - name: Prepare for out-of-source Sphinx build
      run: |
        rm -rf ./build
        mkdir ./build
        python ./utils/build_preparation.py . ./build

    - name: Diagnostic
      run: |
        ls -lAFGh
        ls -lAFGh ./build
        ls -lAFgh ./build/manual/build/

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        # path to conf.py directory
        documentation_path: build/manual/source

    # - name: Push changes if refs/tags
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: gh-pages