name: Publish Sphinx Docs to GitHub Pages
on: [push]

# see: https://sphinx-notes.github.io/pages/
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Install build requirements
      run: |
        pip install -r requirements.txt

    - name: Diagnostic
      run: |
        pip list

    - name: Run the test suite
      run: |
        python utils/test_suite.py

    - name: Prepare for out-of-source Sphinx build
      run: |
        rm -rf ./build
        mkdir ./build
        python ./utils/build_preparation.py . ./build

    - name: Diagnostic
      run: |
        ls -lAFGh
        ls -lAFGh ./build

    - name: Install LaTeX
      run: |
        sudo apt-get update -y && \
        sudo apt-get install -y \
          latexmk \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended

    - name: Build impatient guide
      run: |
        make -C build/impatient-guide html latexpdf

    - name: Build PDF of manual
      run: |
        # expect next make (PDF) to fail (thus exit 0) since nexus.ind not found first time
        # extra option needed to satisfy "levels nested too deeply" error
        (make latexpdf LATEXOPTS="--interaction=nonstopmode" -C build/manual || exit 0)
        # make that missing file
        makeindex build/manual/build/latex/nexus.idx
        # build the PDF, still a failure will be noted but we can ignore it without problem
        (make latexpdf LATEXOPTS="--interaction=nonstopmode" -C build/manual || exit 0)
        # finally, report what was built
        echo "HTML built: `ls -lAFgh build/manual/build/html/*.html`"
        echo "PDF built: `ls -lAFgh build/manual/build/latex/*.pdf`"

    - name: Diagnostic
      run: |
        ls -lAFGh
        ls -lAFGh ./build/manual/build

    # - name: Build and Commit
    #   uses: sphinx-notes/pages@master
    #   with:
    #     # path to conf.py directory
    #     documentation_path: build/manual/source

    # - name: Push changes if refs/tags
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: gh-pages