name: Syntax Checks

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Install build requirements
      run: |
        pip install -r requirements.txt

    - name: Diagnostics
      shell: bash -l {0}
      run: |
        pwd
        ls -lart

        pip list
        printenv | sort

    - name: Run tests
      shell: bash -l {0}
      run: |
        make test

    - name: Build the documentation
      shell: bash -l {0}
      run: |
        make prepare
        make -C build nxdl2rst html
        ls -lAGh
